name: Deploy solid

on:
  pull_request:
  push:
    branches:
      - solid

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build
        env:
          VITE_API_LINK: https://comgrid.ru:8443
          VITE_VK_LOGIN_URI: /oauth2/authorize/vk
          VITE_GOOGLE_LOGIN_URI: /oauth2/authorize/google

          VITE_AUTHORIZATION_REDIRECT_URI: https://comgrid.ru:444/login

      - name: Add ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_SERVER }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Add known hosts
        run: ssh-keyscan -p ${{ secrets.HOST_PORT }} -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST }}:/var/www/html/public/test/