name: NodeJS with Gulp

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'
      
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Build
      run: |
        npm install
        gulp table-page
        
    - name: Deploy via ssh
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_SERVER }} 
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
      
    - name: Deploy with rsync
      run: rsync -avz ./public/ ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST }}:/var/www/html/public/


